apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodbanks-web
  labels:
    app: foodbanks-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodbanks-web
  template:
    metadata:
      labels:
        app: foodbanks-web
    spec:
      serviceAccountName: foodbanks-web
      containers:
        - name: foodbanks-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
